# Generated by Django 4.0.6 on 2022-07-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructCVapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infocvmodel',
            options={'verbose_name': 'infoCVModel', 'verbose_name_plural': 'infoCVModels'},
        ),
        migrations.AddField(
            model_name='infocvmodel',
            name='fileCV',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
