# Generated by Django 4.0.6 on 2022-07-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructCVapp', '0003_alter_infocvmodel_filecv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocvmodel',
            name='fileCV',
            field=models.FileField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
