# Generated by Django 4.0.6 on 2022-07-20 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constructCVapp', '0004_alter_infocvmodel_filecv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocvmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
