# Generated by Django 4.0.6 on 2022-07-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructCVapp', '0005_alter_infocvmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocvmodel',
            name='fileCV',
        ),
    ]
