# Generated by Django 4.0.6 on 2022-07-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructCVapp', '0006_remove_infocvmodel_filecv'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocvmodel',
            name='fileCV',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
