# Generated by Django 4.0.6 on 2022-07-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructCVapp', '0008_infocvmodel_emailadress_infocvmodel_githublink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocvmodel',
            name='wantedJobTitle',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
