# Generated by Django 4.0.6 on 2022-07-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructCVapp', '0009_infocvmodel_wantedjobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocvmodel',
            name='educationSubscribe',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
