# Generated by Django 4.0.6 on 2022-08-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructCVapp', '0011_infocvmodel_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='stackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=25)),
                ('field2', models.CharField(max_length=25)),
                ('field3', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='infocvmodel',
            name='stackFields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructCVapp.stackmodel'),
        ),
    ]
